### PR TITLE
chore(#29): Add data audit brac models

### PR DESCRIPTION
**Pull request by lorerod**
Add data audit to BRAC dbt models

### CODE REVIEW

**Comment by lorerod** [comment]
@njuguna-n I implemented audits for both `impact_pncview_visit` and `impact_pncview_expected_enrollments` using only the macro [compare_queries](https://docs.getdbt.com/blog/audit-helper-for-migration#the-code-for-the-compare_queries-macro-step-by-step). Do you think using this macro is enough? Love to know your thoughts. 
Also, will you want me to continue with all the PNC models? Or are you already making progress on those?

**Comment by andrablaj** [comment]
@lorerod & @njuguna-n, can you please support with answering the following questions:

- Is the approach started by @lorerod supporting the needs of this activity?
- What are the remaining models to audit?

**Comment by lorerod** [comment]
> Is the approach started by @lorerod supporting the needs of this activity?

I started implementing auditing macros using the 'audit_helper' package. This package's primary purpose is to help with the table auditing process and ensure that a refactored model provides the same output as the original one. Although it is not useful for the comparison we are doing now between couch2pg queries and cht-pipeline models, it will be helpful when we refactor existing models. However, as priorities changed, I decided to help Njuguna by providing a manual comparison of the widgets and data sources.

> What are the remaining models to audit?

I only implemented three models, so much remains to be done.

To keep things organized, I'm going to separate this PR from the [Data audit for BRAC models](https://github.com/medic/cht-pipeline/issues/29#top) issue and initiate a new issue for audit for refactoring purposes. We can prioritize it for later.

**Comment by lorerod** [comment]
Also, I will make that issue related to the default models, not the BRAC models.

**Comment by lorerod** [comment]
I will use this draft PR as an example of how to implement auditing on models at https://github.com/medic/cht-pipeline/issues/80

**Comment by andrablaj** [comment]
@lorerod given the pipeline model changes, is this PR still relevant?

**Comment by lorerod** [comment]
This PR is not relevant anymore. Thanks, @andrablaj, for the cleanup.

**Pull request closed without merging**
