### PR TITLE
Fix hard coded dbconnection

### PR DESCRIPTION
**Pull request by njuguna-n**

### CODE REVIEW

**Review by lorerod — APPROVED** [review]
Thanks!

**Review by lorerod — CHANGES_REQUESTED** [review]
We need to add to `tests/run_dbt_tests.sh`:
```
export POSTGRES_USER=root
export POSTGRES_PASSWORD=supercoolpassword
export POSTGRES_SCHEMA=v1
```

**Comment by njuguna-n** [comment]
@lorerod I have added POSTGRES_USER test script, the other variables were already present.

**Review by lorerod — APPROVED** [review]

**Comment by lorerod** [comment]
It is named differently, though. We need to add 
```
export POSTGRES_PASSWORD=supercoolpassword
export POSTGRES_SCHEMA=v1
```
And, also there is a dependency that is out of date:
```
Installing calogica/dbt_date
Installed from version 0.9.1
 Updated version available: 0.10.0
[15](https://github.com/medic/cht-pipeline/actions/runs/6825693693/job/18567603460?pr=41#step:10:16):42:54  
Updates available for packages: ['calogica/dbt_date']                 
Update your versions in packages.yml, then run dbt deps
```

**Comment by njuguna-n** [comment]
Thanks. I have added the variables and updated the package.

**Comment by njuguna-n** [comment]
This PR is still failing because it can't find `v1.couchdb`. I will fix that in this [ticket](https://github.com/medic/cht-pipeline/issues/40).

**Comment by lorerod** [comment]
@njuguna-n Can this be merged to BRAC-models now?

**Pull request merged**
