### PR TITLE
90 base models

### LINKED ISSUE #90: Create base models for CHT

### PR DESCRIPTION
**Pull request by njuguna-n**
Closes #90

### CODE REVIEW

**Comment by andrablaj** [comment]
@njuguna-n, I see the related branch being merged to `BRAC-models` branch for this PR. As the base models should be available as a starting point for every deployment, shouldn't this branch target the `main` branch?

**Comment by njuguna-n** [comment]
That's a great point @andrablaj. I automatically used `BRAC-models` since I have been using for the performance tests. I will update the PR.

**Comment by andrablaj** [comment]
@njuguna-n can you please mention the reasoning behind closing this PR?

**Comment by njuguna-n** [comment]
@andrablaj as you pointed out in this comment the target branch for the base models should be main. This PR is replaced by [this](https://github.com/medic/cht-pipeline/pull/97) one.

**Pull request closed without merging**
