### PR TITLE
BRAC models: Take 1

### PR DESCRIPTION
**Pull request by derickl**

### CODE REVIEW

**Comment by aodhan-domhnaill** [comment]
The `dbt_packages` directory should be removed

**Comment by samuelimoisili** [comment]
@njogz Is this PR still valid? And do we plan on adding it to the cht-pipeline?

**Comment by andrablaj** [comment]
@njogz what is the difference between this PR created by @derickl and the one opened yesterday https://github.com/medic/cht-pipeline/pull/26?

**Comment by andrablaj** [comment]
@njuguna-n what is the difference between this PR created by @derickl and the one opened by you https://github.com/medic/cht-pipeline/pull/26? Most of the files seem identical, would it be a good option to continue the work on this branch directly?

**Comment by njuguna-n** [comment]
@andrablaj the other PR builds on top of this one that is why many of the files are the same. We can safely close this PR.

**Pull request closed without merging**
