### PR TITLE
feat(#144): add macros to reduce boilerplate

### PR DESCRIPTION
**Pull request by witash**
This PR adds the cht_form_model and cht_contact_model macros
Also some small tweaks to person and place models to align with cht-datasource and fix the conditions.
Adds contact_type model to store any metadata about contact types, currently only whether or not the contact type is a person or a place.

Then using this model as the condition for person and place models.
contact_types use the settings document (which should be copied into the source table like any other document) to populate the possible contact types and tell which ones are person and which ones are place.
but there can be other types that are not in the settings, so also just gets distinct contact_type strings from contact, assuming that they are not person unless explicitly called person

### CODE REVIEW

**Comment by witash** [comment]
@lorerod I'm stumped on this test failure https://github.com/medic/cht-pipeline/actions/runs/10697829876/job/29655859067?pr=155#step:5:609 which says that the contact_type table doesn't exist. The data tests show it being created normally, and it's own unit tests pass, so it definitely does exist. did you ever run into any similar errors when creating the unit tests? any ideas what the issue could be?

**Comment by lorerod** [comment]
Hi @witash I didn't encouter this problem before. This is in `dbt/logs/dbt.log`:
```
[0m14:40:35.317559 [debug] [Thread-1 (]: Began running node unit_test.cht_pipeline_base.person.test_person_model_transformation_and_data_integrity
[0m14:40:35.318076 [info ] [Thread-1 (]: 33 of 35 START unit_test person::test_person_model_transformation_and_data_integrity  [RUN]
[0m14:40:35.318850 [debug] [Thread-1 (]: Re-using an available connection from the pool (formerly unit_test.cht_pipeline_base.patient.test_patient_model_transformation_and_data_integrity, now unit_test.cht_pipeline_base.person.test_person_model_transformation_and_data_integrity)
[0m14:40:35.319443 [debug] [Thread-1 (]: Began compiling node unit_test.cht_pipeline_base.person.test_person_model_transformation_and_data_integrity
[0m14:40:35.319912 [debug] [Thread-1 (]: Began executing node unit_test.cht_pipeline_base.person.test_person_model_transformation_and_data_integrity
[0m14:40:35.339272 [debug] [Thread-1 (]: Using postgres connection "unit_test.cht_pipeline_base.person.test_person_model_transformation_and_data_integrity"
[0m14:40:35.339799 [debug] [Thread-1 (]: On unit_test.cht_pipeline_base.person.test_person_model_transformation_and_data_integrity: BEGIN
[0m14:40:35.340153 [debug] [Thread-1 (]: Opening a new connection, currently in state closed
[0m14:40:35.349294 [debug] [Thread-1 (]: SQL status: BEGIN in 0.009 seconds
[0m14:40:35.349782 [debug] [Thread-1 (]: Using postgres connection "unit_test.cht_pipeline_base.person.test_person_model_transformation_and_data_integrity"
[0m14:40:35.350431 [debug] [Thread-1 (]: On unit_test.cht_pipeline_base.person.test_person_model_transformation_and_data_integrity: /* {"app": "dbt", "dbt_version": "1.8.6", "profile_name": "default", "target_name": "test", "node_id": "unit_test.cht_pipeline_base.person.test_person_model_transformation_and_data_integrity"} */

      select
          column_name,
          data_type,
          character_maximum_length,
          numeric_precision,
          numeric_scale

      from "pipelinetest".INFORMATION_SCHEMA.columns
      where table_name = 'contact'
        
        and table_schema = 'v1'
        
      order by ordinal_position

  
[0m14:40:35.360037 [debug] [Thread-1 (]: SQL status: SELECT 9 in 0.009 seconds
[0m14:40:35.367803 [debug] [Thread-1 (]: Writing injected SQL for node "unit_test.cht_pipeline_base.person.test_person_model_transformation_and_data_integrity"
[0m14:40:35.375596 [debug] [Thread-1 (]: Using postgres connection "unit_test.cht_pipeline_base.person.test_person_model_transformation_and_data_integrity"
[0m14:40:35.376035 [debug] [Thread-1 (]: On unit_test.cht_pipeline_base.person.test_person_model_transformation_and_data_integrity: /* {"app": "dbt", "dbt_version": "1.8.6", "profile_name": "default", "target_name": "test", "node_id": "unit_test.cht_pipeline_base.person.test_person_model_transformation_and_data_integrity"} */

      select
          column_name,
          data_type,
          character_maximum_length,
          numeric_precision,
          numeric_scale

      from "pipelinetest".INFORMATION_SCHEMA.columns
      where table_name = 'contact_type'
        
        and table_schema = 'v1'
        
      order by ordinal_position

  
[0m14:40:35.379141 [debug] [Thread-1 (]: SQL status: SELECT 0 in 0.003 seconds
[0m14:40:35.381429 [debug] [Thread-1 (]: On unit_test.cht_pipeline_base.person.test_person_model_transformation_and_data_integrity: ROLLBACK
[0m14:40:35.382208 [debug] [Thread-1 (]: On unit_test.cht_pipeline_base.person.test_person_model_transformation_and_data_integrity: Close
[0m14:40:35.386175 [debug] [Thread-1 (]: Compilation Error in model contact_type (models/contacts/tests/persons.yml)
  Not able to get columns for unit test 'contact_type' from relation "pipelinetest"."v1"."contact_type" because the relation doesn't exist
  
  > in macro get_fixture_sql (macros/unit_test_sql/get_fixture_sql.sql)
  > called by model contact_type (models/contacts/tests/persons.yml)
[0m14:40:35.386928 [error] [Thread-1 (]: 33 of 35 ERROR person::test_person_model_transformation_and_data_integrity ..... [[31mERROR[0m in 0.07s]
[0m14:40:35.387738 [debug] [Thread-1 (]: Finished running node unit_test.cht_pipeline_base.person.test_person_model_transformation_and_data_integrity
```

It seems that materialized views might not show up in `INFORMATION_SCHEMA.columns` used in get_fixture_sql.sql.

**Comment by witash** [comment]
> It seems that materialized views might not show up in `INFORMATION_SCHEMA`. Does this mean we cannot implement a unit test if the model depends on a materialized view? I will read around to see what I can find out.

https://docs.getdbt.com/docs/build/unit-tests#unit-testing-a-model-that-depend-on-ephemeral-models

thanks, this is the problem. Unfortunately the unit tests have some different behavior than `dbt run` which is disappointing, and I don't totally understand why. but a workaround is to change it to incremental with no incremental condition.

**Review by njuguna-n — APPROVED** [review]
Looks good

**Review by lorerod — APPROVED** [review]
LGTM. Thanks

**Pull request merged**
