### PR TITLE
21 add dbt unit test

### PR DESCRIPTION
**Pull request by lorerod**
Implement initial setup for running dbt tests.
Implement unit test for dbt models.
Implement CI workflow to run the tests.

Closes https://github.com/medic/cht-pipeline/issues/21

### CODE REVIEW

**Comment by lorerod** [comment]
Hi, @njogz @samuelimoisili. The idea is to add more tests and specific seed data, but it would be helpful if you could provide some feedback at this point. Thanks!

**Review by samuelimoisili — APPROVED** [review]

**Comment by lorerod** [comment]
> This is great Lorena. I have followed the instructions and I get the error below when running the setup script. Is that an error you have experienced or is it something with my local environment. `psql: error: connection to server at "localhost" (::1), port 5432 failed: FATAL: role "root" does not exist`

Thanks for testing @njogz. It didn't happen to me. It is weird, as in line 3 of the setup.sh the POSTGRES_USER is set up. 
One step I didn't document is to change permissions on the shell with `chmod u+rwx setup.sh` 
Can you try that while I continue looking into the error?

**Comment by lorerod** [comment]
@njogz I wasn't able to reproduce the error you are experiencing. Please check if you don't have your local Postgres up or something similar, and if you do, please stop and quit the local Postgres instance before executing the scripts on this repo.
you can also try Postgres and python installation before executing the scripts:
1. Install PostgreSQL client
          sudo apt-get update
          sudo apt-get install --yes postgresql-client
2. Set up Python (python-version: "3.8")
3. Install dbt postgres
           pip install dbt-postgres
Please let me know if you were able to execute all scripts successfully. Thanks!

**Review by njuguna-n — APPROVED** [review]
I am getting  a  different error  now  related to  python when I  run ./run_dbt_tests.sh.  The  error is  `AttributeError: module 'collections' has no attribute 'MutableMapping'AttributeError: module 'collections' has no attribute 'MutableMapping'`. Approving now  to  unblock you.

**Pull request merged**
